-- MySQL Script generated by MySQL Workbench
-- jue 26 mar 2020 14:39:29 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ANBU_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ANBU_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ANBU_DB` DEFAULT CHARACTER SET utf8 ;
USE `ANBU_DB` ;

-- -----------------------------------------------------
-- Table `ANBU_DB`.`Busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANBU_DB`.`Busqueda` (
  `idBusqueda` INT NOT NULL AUTO_INCREMENT,
  `nombre_buscado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idBusqueda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANBU_DB`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANBU_DB`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `urlPerfil` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANBU_DB`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANBU_DB`.`Publicacion` (
  `idPublicacion` INT NOT NULL AUTO_INCREMENT,
  `idPerfil` INT NULL,
  `ubicacion` VARCHAR(100) NULL,
  `fecha` DATETIME NULL,
  `enlace` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `val_rostro` INT(1) NULL,
  `val_arma` INT(1) NULL,
  `ruta_imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `idPerfil_idx` (`idPerfil` ASC),
  CONSTRAINT `idPerfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `ANBU_DB`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANBU_DB`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANBU_DB`.`Reporte` (
  `idReporte` INT NOT NULL AUTO_INCREMENT,
  `numPerfiles` INT NULL,
  `numPerfilesArma` INT NULL,
  `numPerfilesRostro` INT NULL,
  PRIMARY KEY (`idReporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANBU_DB`.`reporte_busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANBU_DB`.`reporte_busqueda` (
  `idBusqueda` INT NOT NULL,
  `idReporte` INT NOT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`idBusqueda`, `idReporte`),
  INDEX `fk_reporte_busquedas_2_idx` (`idReporte` ASC),
  CONSTRAINT `fk_reporte_busquedas_1`
    FOREIGN KEY (`idBusqueda`)
    REFERENCES `ANBU_DB`.`Busqueda` (`idBusqueda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_busquedas_2`
    FOREIGN KEY (`idReporte`)
    REFERENCES `ANBU_DB`.`Reporte` (`idReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANBU_DB`.`busqueda_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANBU_DB`.`busqueda_perfil` (
  `idBusqueda` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`idBusqueda`, `idPerfil`),
  INDEX `fk_busqueda_perfil_2_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_busqueda_perfil_1`
    FOREIGN KEY (`idBusqueda`)
    REFERENCES `ANBU_DB`.`Busqueda` (`idBusqueda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_busqueda_perfil_2`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `ANBU_DB`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANBU_DB`.`Rostro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANBU_DB`.`Rostro` (
  `idRostro` INT NOT NULL AUTO_INCREMENT,
  `idPublicacion` INT NULL,
  `rostro_oval` INT NULL,
  `entradas` INT NULL COMMENT '						',
  `cejas_pobladas` INT NULL,
  `cejas_arco` INT NULL,
  `pomulos` INT NULL,
  `nariz_grande` INT NULL,
  `nariz_puntiaguda` INT NULL,
  `labios_grandes` INT NULL,
  `barbilla_partida` INT NULL,
  `evaluacion_rostro` INT NULL,
  PRIMARY KEY (`idRostro`),
  INDEX `fk_Rostro_1_idx` (`idPublicacion` ASC),
  CONSTRAINT `fk_Rostro_1`
    FOREIGN KEY (`idPublicacion`)
    REFERENCES `ANBU_DB`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ANBU_DB`.`Arma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANBU_DB`.`Arma` (
  `idArma` INT NOT NULL,
  `idPublicacion` INT NULL,
  `porcentaje` INT NULL,
  `evaluacion_arma` INT NULL,
  PRIMARY KEY (`idArma`),
  INDEX `fk_Arma_1_idx` (`idPublicacion` ASC),
  CONSTRAINT `fk_Arma_1`
    FOREIGN KEY (`idPublicacion`)
    REFERENCES `ANBU_DB`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
