-- MySQL Script generated by MySQL Workbench
-- dom 29 mar 2020 17:47:45 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema anbuDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anbuDB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `anbuDB`;
ALTER DATABASE anbuDB
CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;
USE `anbuDB` ;

-- -----------------------------------------------------
-- Table `anbuDB`.`Busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anbuDB`.`Busqueda` (
  `idBusqueda` INT NOT NULL AUTO_INCREMENT,
  `nombre_buscado` VARCHAR(30) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idBusqueda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anbuDB`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anbuDB`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `urlPerfil` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anbuDB`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anbuDB`.`Publicacion` (
  `idPublicacion` INT NOT NULL AUTO_INCREMENT,
  `idPerfil` INT NOT NULL,
  `ubicacion` VARCHAR(100) NULL,
  `fecha` DATETIME NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `descripcion` VARCHAR(2200) NULL,
  `val_rostro` INT(1) NULL,
  `val_arma` INT(1) NULL,
  `ruta_imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `idPerfil_idx` (`idPerfil` ASC),
  CONSTRAINT `idPerfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `anbuDB`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anbuDB`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anbuDB`.`Reporte` (
  `idReporte` INT NOT NULL AUTO_INCREMENT,
  `numPerfiles` INT NULL,
  `numPerfilesArma` INT NULL,
  `numPerfilesRostro` INT NULL,
  PRIMARY KEY (`idReporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anbuDB`.`reporte_busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anbuDB`.`reporte_busqueda` (
  `idBusqueda` INT NOT NULL,
  `idReporte` INT NOT NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`idBusqueda`, `idReporte`),
  INDEX `fk_reporte_busquedas_2_idx` (`idReporte` ASC),
  CONSTRAINT `fk_reporte_busquedas_1`
    FOREIGN KEY (`idBusqueda`)
    REFERENCES `anbuDB`.`Busqueda` (`idBusqueda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_busquedas_2`
    FOREIGN KEY (`idReporte`)
    REFERENCES `anbuDB`.`Reporte` (`idReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anbuDB`.`busqueda_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anbuDB`.`busqueda_perfil` (
  `idBusqueda` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idBusqueda`, `idPerfil`),
  INDEX `fk_busqueda_perfil_2_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_busqueda_perfil_1`
    FOREIGN KEY (`idBusqueda`)
    REFERENCES `anbuDB`.`Busqueda` (`idBusqueda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_busqueda_perfil_2`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `anbuDB`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anbuDB`.`Rostro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anbuDB`.`Rostro` (
  `idRostro` INT NOT NULL AUTO_INCREMENT,
  `idPublicacion` INT NULL,
  `rostro_oval` INT NULL,
  `entradas` INT NULL COMMENT '           ',
  `cejas_pobladas` INT NULL,
  `cejas_arco` INT NULL,
  `pomulos` INT NULL,
  `nariz_grande` INT NULL,
  `nariz_puntiaguda` INT NULL,
  `labios_grandes` INT NULL,
  `barbilla_partida` INT NULL,
  `evaluacion_rostro` INT NULL,
  PRIMARY KEY (`idRostro`),
  INDEX `fk_Rostro_1_idx` (`idPublicacion` ASC),
  CONSTRAINT `fk_Rostro_1`
    FOREIGN KEY (`idPublicacion`)
    REFERENCES `anbuDB`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `anbuDB`.`Arma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anbuDB`.`Arma` (
  `idArma` INT NOT NULL,
  `idPublicacion` INT NULL,
  `porcentaje` INT NULL,
  `evaluacion_arma` INT NULL,
  PRIMARY KEY (`idArma`),
  INDEX `fk_Arma_1_idx` (`idPublicacion` ASC),
  CONSTRAINT `fk_Arma_1`
    FOREIGN KEY (`idPublicacion`)
    REFERENCES `anbuDB`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
